spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/car_crud_db
    username: test
    password: test
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update